### ISSUE TITLE
sqrt(): argument 'input' (position 1) must be Tensor, not int

### ISSUE THREAD

**Issue by slusarczyk41** [pytorch/fairseq#1734]
## 🐛 Bug

When using fairseq-train with RoBERTa model after 37 CUDA OOM's I get this error:
TypeError: sqrt(): argument 'input' (position 1) must be Tensor, not int

### Cmd I used
```
fairseq-train 'data-bin/agora' \
    --task masked_lm --criterion masked_lm \
    --arch roberta_base --sample-break-mode complete --tokens-per-sample 512 \
    --optimizer adam --adam-betas '(0.9,0.98)' --adam-eps 1e-6 --clip-norm 0.0 \
    --lr-scheduler polynomial_decay --lr 0.0005 --warmup-updates 50 \
    --total-num-update 100 \
    --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.01 \
    --max-sentences 6 --update-freq 40 \
    --max-update 100 --log-format simple --log-interval 1 \
    --restore-file 'roberta/checkpoint_best.pt' --save-dir 'my_models/agora' \
    --skip-invalid-size-inputs-valid-test --reset-optimizer
```
- pretrained model downloaded from: https://github.com/sdadas/polish-nlp-resources/releases/download/roberta/roberta.zip
### Traceback I got
```
2020-02-21 13:40:23 | WARNING | fairseq.trainer | attempting to recover from OOM in forward/backward pass
Traceback (most recent call last):
  File "/home/jacek/anaconda3/envs/py36/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/home/jacek/Projects/fairseq/fairseq_cli/train.py", line 307, in cli_main
    main(args)
  File "/home/jacek/Projects/fairseq/fairseq_cli/train.py", line 102, in main
    train(args, trainer, task, epoch_itr)
  File "/home/jacek/anaconda3/envs/py36/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/jacek/Projects/fairseq/fairseq_cli/train.py", line 171, in train
    log_output = trainer.train_step(samples)
  File "/home/jacek/anaconda3/envs/py36/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/jacek/Projects/fairseq/fairseq/trainer.py", line 369, in train_step
    grad_norm = self.optimizer.clip_grad_norm(self.args.clip_norm)
  File "/home/jacek/Projects/fairseq/fairseq/optim/fairseq_optimizer.py", line 91, in clip_grad_norm
    return utils.clip_grad_norm_(self.params, max_norm)
  File "/home/jacek/Projects/fairseq/fairseq/utils.py", line 243, in clip_grad_norm_
    sum(p.grad.data.norm()**2 for p in params if p.grad is not None)
TypeError: sqrt(): argument 'input' (position 1) must be Tensor, not int
```

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0) 1.4.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed fairseq (`pip`, source): pip install --editable .
 - Python version: 3.6.9 Anaconda
 - CUDA/cuDNN version: ?
 - GPU models and configuration: 750 TI

**Comment by myleott** [comment]
Your training command works for me. Are you sure you're on pytorch 1.4?

**Comment by slusarczyk41** [comment]
Yes it is 1.4. I will add tomorrow data needed to reproduce it. The thing is that command works, it trains model for about a minute and then throws an exception.

**Comment by myleott** [comment]
You mentioned seeing numerous OOMs. Does it work if you reduce the batch size so you don't OOM?

**Comment by slusarczyk41** [comment]
After changing to better GPU I didn't have any OOMs, and that problem vanished as well.
