### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: cudaErrorMisalignedAddress: misaligned address

### ISSUE THREAD

**Issue by thies1006** [pytorch/fairseq#2518]
I am trying to train a machine translation model using model parallelism like shown in the megatron example. I have two machines with 6 GPUs each (Nvidia Titan RTX). However when using ```--fp16``` or ```--memory-efficient-fp16``` I get the error 
```terminate called after throwing an instance of 'c10::Error'```
```what():  CUDA error: misaligned address (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:764)```
```frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fd87bb7e193 in /secondary/thies/.virtualenvs/pytorch-1.4/lib/python3.6/site-packages/torch/lib/libc10.so)```
...
(breaks right at the beginning of the training)

Apparently it works when I remove the fp16 option.
When using FP16 I figured out that when I switch to 4 GPUs per worker (plus tweaking the model/dictionary to make it divisible by 4) it is also training. 

The megatron example (language model) works fine, with FP16 and 6 GPUs per worker.

Setup:
ubuntu 18.04
cuda10.1
pytorch 1.4.0

Any ideas?
Thanks

**Comment by alexeib** [comment]
looks like a pytorch error, maybe open an issue there? does everything work if you use no_c10d backend?

**Comment by thies1006** [comment]
Strange, with no_c10d backend I still get the same error. 
I'll close this one then and open another issue at pytorch, thx.

**Comment by thies1006** [comment]
After compiling pytorch-nightly (version today) the error went away. Just in case somebody meets this strange error.
