### ISSUE TITLE
OOM occurred during the middle of training

### ISSUE THREAD

**Issue by monologue1107** [pytorch/fairseq#2867]
I can fine-tune the model at first, even it can train entirely in epoch 1. However, it will become OOM in epoch 2 around 4517/21194. I tried to change scripts like total_num_updates or update_freq several times, but it did't help.
Do you have some idea the OOM problem occurred in the middle part of training and give me some tips? Looking forward for your kindly help.
The log shows like below:

```
2020-11-06 22:55:35 | WARNING | fairseq.trainer | OOM: Ran out of memory with exception: CUDA out of memory. Tried to allocate 28.00 MiB (GPU 1; 10.92 GiB total capacity; 10.13 GiB already allocated; 13.38 MiB free; 10.33 GiB reserved in total by PyTorch)
...
2020-11-06 22:55:35 | WARNING | fairseq.trainer | attempting to recover from OOM in forward/backward pass
Traceback (most recent call last):
  File "/data/rwd/anaconda3/envs/fairseq/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/data/rwd/fairseq/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/data/rwd/fairseq/fairseq/distributed_utils.py", line 254, in call_main
    nprocs=args.distributed_num_procs,
  File "/data/rwd/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/data/rwd/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/data/rwd/fairseq/fairseq/distributed_utils.py", line 339, in all_gather_list
    result.append(pickle.loads(bytes(out_buffer[header_size:header_size + enc_size].tolist())))
_pickle.UnpicklingError: unpickling stack underflow
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/data/rwd/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/data/rwd/fairseq/fairseq/distributed_utils.py", line 238, in distributed_main
    main(args, **kwargs)
  File "/data/rwd/fairseq/fairseq_cli/train.py", line 125, in main
    valid_losses, should_stop = train(args, trainer, task, epoch_itr)
  File "/data/rwd/anaconda3/envs/fairseq/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/data/rwd/fairseq/fairseq_cli/train.py", line 208, in train
    log_output = trainer.train_step(samples)
  File "/data/rwd/anaconda3/envs/fairseq/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/data/rwd/fairseq/fairseq/trainer.py", line 531, in train_step
    logging_outputs, sample_size, ooms, train_time, ignore=is_dummy_batch,
  File "/data/rwd/fairseq/fairseq/trainer.py", line 885, in _aggregate_logging_outputs
    logging_outputs, *extra_stats_to_sum, ignore=ignore
  File "/data/rwd/fairseq/fairseq/trainer.py", line 906, in _all_gather_list_sync
    group=self.data_parallel_process_group,
  File "/data/rwd/fairseq/fairseq/distributed_utils.py", line 343, in all_gather_list
    'Unable to unpickle data from other workers. all_gather_list requires all '
Exception: Unable to unpickle data from other workers. all_gather_list requires all workers to enter the function together, so this error usually indicates that the workers have fallen out of sync somehow. Workers can fall out of sync if one of them runs out of memory, or if there are other conditions in your training script that can cause one worker to finish an epoch while other workers are still iterating over their portions of the data. Try rerunning with --ddp-backend=no_c10d and see if that helps.
```

**Comment by monologue1107** [comment]
My GPUs are 3*11GB(1080Ti)
Here are my command line:
```
TOTAL_NUM_UPDATES=1000000
WARMUP_UPDATES=500
LR=3e-05
MAX_TOKENS=1024
UPDATE_FREQ=1
BART_PATH=/data/rwd/fairseq/bart.large/model.pt

CUDA_VISIBLE_DEVICES=0,1,2 fairseq-train cnn_dm-bin \
    --restore-file $BART_PATH \
    --max-tokens $MAX_TOKENS \
    --task translation \
    --source-lang source --target-lang target \
    --truncate-source \
    --layernorm-embedding \
    --share-all-embeddings \
    --share-decoder-input-output-embed \
    --reset-optimizer --reset-dataloader --reset-meters \
    --required-batch-size-multiple 1 \
    --arch bart_large \
    --criterion label_smoothed_cross_entropy \
    --dropout 0.1 --attention-dropout 0.1 \
    --label-smoothing 0.1 \
    --weight-decay 0.01 --optimizer adam --adam-betas "(0.9, 0.999)" --adam-eps 1e-08 \
    --clip-norm 0.1 \
    --lr-scheduler polynomial_decay --lr $LR --total-num-update $TOTAL_NUM_UPDATES --warmup-updates $WARMUP_UPDATES \
    --update-freq $UPDATE_FREQ \
    --memory-efficient-fp16 \
    --skip-invalid-size-inputs-valid-test \
    --tensorboard-logdir './logs6/' \
    --find-unused-parameters &
```

**Comment by alexeib** [comment]
have you tried following the suggestion and using --ddp-backend=no_c10d?

**Comment by monologue1107** [comment]
> have you tried following the suggestion and using --ddp-backend=no_c10d?

I just tried with this command. The upper problem has been solved while there seems to be occurred another problem.
When I training my code, it have these mistakes:
```
2020-11-08 23:47:40 | WARNING | fairseq.trainer | attempting to recover from OOM in forward/backward pass
/data/rwd/anaconda3/envs/fairseq/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 6 leaked semaphores to clean up at shutdown
  len(cache))
```
Besides, it seems to even shut down my gpus. When I use 'nvidia-smi', it shows:
`Unable to determine the device handle for GPU 0000:0D:00.0: GPU is lost.  Reboot the system to recover this GPU`
I have to reboot the computer so that it can become normal. Have you ever seen this kind of problems?

**Comment by alexeib** [comment]
i have not seen this before. have you tried updating your gpu drivers etc?

**Comment by monologue1107** [comment]
> i have not seen this before. have you tried updating your gpu drivers etc?

I don't have root access since I run this code on server. So updating gpu drivers seems to be difficult for me.
What about the another error:
```
2020-11-08 23:47:40 | WARNING | fairseq.trainer | attempting to recover from OOM in forward/backward pass
/data/rwd/anaconda3/envs/fairseq/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 6 leaked semaphores to clean up at shutdown
  len(cache))
```
I don't know if my code is mistaken or what. It may related to the gpu driver problem or not.

**Comment by alexeib** [comment]
the semaphore thing comes from dataloader processes that asynchronously load data. thats the message you get if you kill the process somehow (e.g. your oom crashes for example)

**Comment by monologue1107** [comment]
> the semaphore thing comes from dataloader processes that asynchronously load data. thats the message you get if you kill the process somehow (e.g. your oom crashes for example)

Thx for your answer. It seems being solved when I add --ddp-backend=no_c10d and decrease the update_freq to 1.

**Comment by liaohit** [comment]
I just tried add --ddp-backend=no_c10d and decrease the update_freq to 1, but the warning still exist.

| WARNING | fairseq.trainer | OOM: Ran out of memory with exception: CUDA out of memory. Tried to allocate 28.00 MiB (GPU 1; 10.92 GiB total capacity; 10.13 GiB already allocated; 13.38 MiB free; 10.33 GiB reserved in total by PyTorch)
| WARNING | fairseq.trainer | attempting to recover from OOM in forward/backward pass
Traceback
