### ISSUE TITLE
RuntimeError :relative position represation transformer within fp16 training

### ISSUE THREAD

**Issue by libeineu** [pytorch/fairseq#646]
fairseq-0.6.2
CUDA 10.0
cudnn 7.4.2
pytorch 1.0.0(cuda10)
8TiTan V GPUS

I implement self-attention with relative-position-represation based transformer on fairseq-0.6.2,and it can work well by float32 training. But it crashed within fp16 training mode. Could you please give me some advices?

Traceback (most recent call last):
  File "train.py", line 415, in <module>
    cli_main()
  File "train.py", line 407, in cli_main
    nprocs=args.distributed_world_size,
  File "/home/libei/Python-3.6.7/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/home/libei/Python-3.6.7/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/libei/Python-3.6.7/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/libei/fairseq-0.6.2/train.py", line 380, in distributed_main
    main(args, init_distributed=True)
  File "/home/libei/fairseq-0.6.2/train.py", line 106, in main
    train(args, trainer, task, epoch_itr)
  File "/home/libei/fairseq-0.6.2/train.py", line 141, in train
    log_output = trainer.train_step(samples)
  File "/home/libei/fairseq-0.6.2/fairseq/trainer.py", line 209, in train_step
    raise e
  File "/home/libei/fairseq-0.6.2/fairseq/trainer.py", line 197, in train_step
    ignore_grad
  File "/home/libei/fairseq-0.6.2/fairseq/tasks/fairseq_task.py", line 231, in train_step
    optimizer.backward(loss)
  File "/home/libei/fairseq-0.6.2/fairseq/optim/fp16_optimizer.py", line 145, in backward
    loss.backward()
  File "/home/libei/Python-3.6.7/lib/python3.6/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/libei/Python-3.6.7/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: merge_sort: failed to synchronize: misaligned address

**Comment by myleott** [comment]
What version of pytorch are you using?

**Comment by libeineu** [comment]
pytorch 1.0.0(cuda10), I both use pytorch-0.4.1 (fiarseq-0.5) and pytorch-1.0.0（fairseq-0.6.2), but same errors

**Comment by myleott** [comment]
Hmm, do you get the same error without your relative positional embeddings? Is it possible your code is overflowing somewhere in FP16, but not in FP32? I'd recommend putting slowly removing elements from your code to debug where the problem is happening.

**Comment by libeineu** [comment]
Ok, it really works in FP32, I will debug my code in your way, thanks!

**Comment by huihuifan** [comment]
Looks resolved (please debug in fp32 and open a new issue if you are having problems, thanks)

**Comment by patrik-lambert** [comment]
Hi @libeineu, this question is not directly related with this post, but since you mention you are using Titan V GPUs, do you know the speed gain you get on these GPUs on a standard training with fairseq with the fp16 mode (compared to fp32)? (on a standard training, that is without relative-position-represation). Thanks.

**Comment by libeineu** [comment]
OK，from the experiment result, I can observe that two times faster than  FP36  when using FP16 training. And it will gain more when the model capacity goes larger.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Patrik Lambert <notifications@github.com>
发送时间: Tuesday, July 9, 2019 10:36:14 PM
收件人: pytorch/fairseq
抄送: LiBei; Mention
主题: Re: [pytorch/fairseq] RuntimeError :relative position represation transformer within fp16 training (#646)


Hi @libeineu<https://github.com/libeineu>, this question is not directly related with this post, but since you mention you are using Titan V GPUs, do you know the speed gain you get on these GPUs on a standard training with fairseq with the fp16 mode (compared to fp32)? (on a standard training, that is without relative-position-represation). Thanks.

―

**Comment by patrik-lambert** [comment]
Thanks!

**Comment by RobotGF** [comment]
I met the same question, and I guess maybe it's a bug in apex, but now I didn't find which code cause the bug? have you  resolved this question?

**Comment by libeineu** [comment]
I found that if we only use the relative position key, we can also achieve comparable performance. And the training process is stable with FP16.

**Comment by RobotGF** [comment]
> I found that if we only use the relative position key, we can also achieve comparable performance. And the training process is stable with FP16.
Thanks for your response. I replaced torch.bmm() with torch.matmul() in the multihead_attention module. And it works for training with FP16.
