### ISSUE TITLE
wav2vec: Gets a cuda -error during the training loop

### ISSUE THREAD

**Issue by shamanez** [pytorch/fairseq#932]
Hi, I tried to train the model on 1000 hrs of librispeech dataset. I have two GPUs (Nvidia 1080 - 11gb each). But it gives a cuda out of memory error and shows the following message. 

_WARNING: ran out of memory with exception: CUDA out of memory. Tried to allocate 1.16 GiB (GPU 0; 10.91 GiB total capacity; 6.55 GiB already allocated; 1.05 GiB free; 1.94 GiB cached);
Skipping batch_

![image](https://user-images.githubusercontent.com/16892570/62154066-1444ea00-b35a-11e9-89ff-f9925825817e.png)

**Comment by mommi84** [comment]
I know this issue was closed years ago, but I solved the memory problem by setting `fp16: false` and `memory_efficient_fp16: true` in the YAML config file. Perhaps this can help others.
