### ISSUE TITLE
unhandled cuda error while training using multiple nodes

### ISSUE THREAD

**Issue by nadongguri** [pytorch/fairseq#973]
Hi, I'm trying to train fconv_lm_dauphin_wikitext103 model with multiple nodes.
 - We have 8 nodes and each node has 4 GPUs(2080 RTX).
 - anaconda, python 3.6
 - pytorch : 1.1.0
 - cuda : 10.0.130
 - cudnn : 7.4.2
 - nccl : 2.3.7

 The problem is that error comes when I set nproc_per_node argument as more than 3. (There's no problem with 1 or 2. I checked it with 3 nodes each uses 2 GPUs.)

 the commands what I used are
```
 for node-0)
 python -m torch.distributed.launch --nproc_per_node=4    --nnodes=2\
 --node_rank=0 --master_addr="192.168.10.104"     --master_port=22549\
$(which fairseq-train) --task language_modeling data-bin/wikitext-103\
--save-dir checkpoints/fconv_wikitext-103_2   --max-epoch 1 
--arch fconv_lm_dauphin_wikitext103 --optimizer nag \
  --lr 1.0 --lr-scheduler reduce_lr_on_plateau --lr-shrink 0.5   --clip-norm 0.1 \
--dropout 0.2 --weight-decay 5e-06 --criterion adaptive_loss  \
 --adaptive-softmax-cutoff 10000,20000,200000\
 --max-tokens 1024 --tokens-per-sample 2048 \
  --ddp-backend=no_c10d --disable-validation --no-save --distributed-no-spawn
```
```
 for node-1) 
 # I only replaced --node_rank as 1
```
 The error is "unhandled cuda error".

[node1] python -m torch.distributed.launch --nproc_per_node=4 --nnodes=2 --node_rank=1 --master_addr="192.168.10.104"     --master_port=22549     $(which fairseq-train) --task language_modeling data-bin/wikitext-103   --save-dir checkpoints/fconv_wikitext-103_2   --max-epoch 1 --arch fconv_lm_dauphin_wikitext103 --optimizer nag   --lr 1.0 --lr-scheduler reduce_lr_on_plateau --lr-shrink 0.5   --clip-norm 0.1 --dropout 0.2 --weight-decay 5e-06 --criterion adaptive_loss   --adaptive-softmax-cutoff 10000,20000,200000 --max-tokens 1024 --tokens-per-sample 1024   --ddp-backend=no_c10d --disable-validation --no-save --distributed-no-spawn
| distributed init (rank 5): env://
| distributed init (rank 7): env://
| distributed init (rank 6): env://
| initialized host c8.rtx as rank 5
| initialized host c8.rtx as rank 6
| initialized host c8.rtx as rank 7
| distributed init (rank 4): env://
| initialized host c8.rtx as rank 4
Traceback (most recent call last):
  File "/home/dongjin/anaconda3/envs/test_3.6/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/home/dongjin/tmp/delete/fairseq2/fairseq_cli/train.py", line 305, in cli_main
    distributed_main(args.device_id, args)
  File "/home/dongjin/tmp/delete/fairseq2/fairseq_cli/train.py", line 284, in distributed_main
    main(args, init_distributed=True)
  File "/home/dongjin/tmp/delete/fairseq2/fairseq_cli/train.py", line 33, in main
    args.distributed_rank = distributed_utils.distributed_init(args)
  File "/home/dongjin/tmp/delete/fairseq2/fairseq/distributed_utils.py", line 92, in distributed_init
    dist.all_reduce(torch.rand(1).cuda())
  File "/home/dongjin/anaconda3/envs/test_3.6/lib/python3.6/site-**packages/torch/distributed/distributed_c10d.py", line 900, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1556653099582/work/torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhandled cuda error**

I wonder if I am missing anything or if anyone succeeded running fairseq on multi-node please let me how you did it.

**Comment by nadongguri** [comment]
I solved this issue. :)
Actually, my script uses nccl 2.3.2 instead of 2.3.7. I'm not sure but adding export NCCL_TREE_THRESHOLD=0 solves the issue even though it decreases the performance.
I will check by installing the latest nccl library. Thanks.
